name: Build and save dist file

on:
  push:
    branches:
      - main
    paths-ignore:
      - "dist/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        run: |
          npm ci
          npm run build
      - name: Save dist file
        run: |
          git add dist
          git commit -m "Update dist file" || true
          git push
